### ISSUE TITLE
names of gene

### ISSUE THREAD

**Issue by xiebb123456** [grisslab/scClassifR#8]
Hi Johannes，

Thanks for the quick response!

I also met another questions, mainly caused by conflict of names genes (symbol).
For example: gene symbol contain '-'  (H2-AB1) or start with digital (0610005C13RIK) will not recognise by classifier.

Good luck!
Bingbing

**Comment by nttvy** [comment]
Hi @xiebb123456,

Thank you a lot for your report. The problem was solved in the recent commit 062a72f.

Additionally, the package has been renamed to scAnnotatR and it's now being submitted again to Bioconductor. If you are interested, please refer to: https://github.com/grisslab/scAnnotatR.

Best regards,
Vy
